obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.35, 0.35], [0.35, -0.35]]
robot_radius: 0.46
inflation_radius: 0.55
observation_sources: scan

scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

map_type: costmap
transform_tolerance: 0.2