global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true

  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0

  obstacle_layer:
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 2.0
    min_obstacle_height: 0.1
    observation_sources: scan
    scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}